In [1]:
import torch 

In [2]:
x = torch.rand(1,2)

In [3]:
x

tensor([[0.1238, 0.6475]])

In [6]:
x

tensor([[0.1238, 0.6475]])

In [10]:
x.zero_()

tensor([[0., 0.]])

In [11]:
x

tensor([[0., 0.]])

In [ ]:
x 