In [1]:
import numpy as np

#### numpy direct computation on array

In [2]:
values = np.random.randint(1, 10, size=10000000)
%timeit (1.0 / values)

6.18 ms ± 64.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### normal 'for' loop computation

In [3]:
def compute_reciprocals(values):           
    output = np.empty(len(values))           
    for i in range(len(values)):               
        output[i] = 1.0 / values[i]           
        return output

%timeit compute_reciprocals(values)

3.23 µs ± 8.69 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [5]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
2 * x

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
x + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [8]:
x ** 5

array([[    0,     1,    32],
       [  243,  1024,  3125],
       [ 7776, 16807, 32768]])

In [9]:
np.add(x, 10)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [10]:
np.power(x, 5)

array([[    0,     1,    32],
       [  243,  1024,  3125],
       [ 7776, 16807, 32768]])

In [11]:
np.log(x + 4)

array([[1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [12]:
theta = np.linspace(0, np.pi, 3)
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [13]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.add.reduce(x)

array([ 9, 12, 15])

In [15]:
np.add.reduce(x, axis=1)

array([ 3, 12, 21])

In [16]:
np.add.accumulate(x)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

### Aggregations

In [17]:
l = np.random.random(100)
sum(l)

50.179978588942795

In [18]:
np.sum(l)

50.1799785889428

In [19]:
l = np.random.random(1000000)
%timeit sum(l)
%timeit np.sum(l)

69.3 ms ± 495 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
195 µs ± 158 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%timeit min(l), max(l)

99.1 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%timeit np.min(l), np.max(l)

357 µs ± 467 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Broadcasting

In [22]:
M = np.ones((2, 3))

In [23]:
a = np.arange(3)

In [24]:
M.shape, a.shape

((2, 3), (3,))

In [25]:
M, a

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2]))

In [26]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [27]:
(M + a).shape

(2, 3)

In [28]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3)

In [29]:
a.shape, b.shape

((3, 1), (3,))

In [30]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [31]:
(a + b).shape

(3, 3)

In [32]:
M = np.arange(6).reshape(3, 2)
a = np.arange(3)

In [33]:
M.shape, a.shape

((3, 2), (3,))

In [ ]:
X = np.random.random((10, 3))

In [ ]:
Xmean = X.mean(0) # default axis 0/'index'
Xmean

In [ ]:
X_centered = X - Xmean

In [ ]:
X.shape

In [ ]:
Xmean.shape

In [ ]:
X_centered.mean(0)

In [ ]:
x = np.linspace(0, 5, 50)        
y = np.linspace(0, 5, 50)[:, np.newaxis]

In [ ]:
x.shape

In [ ]:
y.shape

### Boolean operators on numpy array

### Indexing operations

### Sorting

### Using structured data with numpy arrays