In [1]:
import torch
import numpy as np
import pandas as pd
import os

## Tensor Operations

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
X.shape

torch.Size([3, 4])

In [8]:
X = x.reshape(3, -1)

In [9]:
X.shape

torch.Size([3, 4])

In [10]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)

tensor([[ 0.7020,  0.8658, -0.0063,  0.6935],
        [ 0.0930,  0.3742,  0.5702,  0.0116],
        [ 0.0775, -2.2366, -1.2064, -0.8677]])

In [14]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
torch.arange(5) + torch.arange(5)

tensor([0, 2, 4, 6, 8])

In [16]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [18]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [19]:
torch.cat((X, Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [22]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
X.sum()

tensor(66.)

In [24]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

In [25]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [26]:
(a + b).shape

torch.Size([3, 2])

In [27]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [29]:
X[-1][3]

tensor(11.)

In [30]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X[1][2] = 600.2

In [33]:
X

tensor([[  0.0000,   1.0000,   2.0000,   3.0000],
        [  4.0000,   5.0000, 600.2000,   7.0000],
        [  8.0000,   9.0000,  10.0000,  11.0000]])

In [34]:
X[0:2, :] = 500

In [35]:
X

tensor([[500., 500., 500., 500.],
        [500., 500., 500., 500.],
        [  8.,   9.,  10.,  11.]])

In [36]:
X[0:3, 0:4] = 0

In [37]:
X

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [39]:
before = id(Y)
Y = Y + X
before == id(Y)

False

In [40]:
before = id(Y)
Y[:] = Y + X
before == id(Y)

True

In [41]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y       # used the same object memory (in-place update)
print('id(Z):', id(Z))

id(Z): 140565735630976
id(Z): 140565735630976


In [42]:
A = np.array([1, 2, 3])
B = torch.tensor(A)
A, B

(array([1, 2, 3]), tensor([1, 2, 3]))

In [43]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [44]:
a = torch.tensor([3.5])
a

tensor([3.5000])

In [45]:
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Reading Data into tensor

In [46]:
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')

In [47]:
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [48]:
data = pd.read_csv('data/house_tiny.csv')
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [49]:
inputs = data.iloc[:, :2]
output = data.iloc[:, 2]

In [50]:
inputs = inputs.fillna(inputs.mean())  # filling with mean value
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [51]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [52]:
X = torch.tensor(inputs.values)
y = torch.tensor(output.values)

In [53]:
X, X.shape

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 torch.Size([4, 3]))

In [54]:
y, y.shape

(tensor([127500, 106000, 178100, 140000]), torch.Size([4]))

In [59]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [55]:
col_most_nan = data.isnull().sum().sort_values(ascending=False).index[0]

In [56]:
col_most_nan

'Alley'

In [57]:
inputs_rem_most_null = data.drop(labels=col_most_nan, axis=1)

In [58]:
inputs_rem_most_null

NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000

## Linear Algebra on Tensors

#### Scalars

In [60]:
x = torch.tensor(3.0)
y = torch.tensor(4.0)

In [61]:
x, y

(tensor(3.), tensor(4.))

In [62]:
x + y, x * y

(tensor(7.), tensor(12.))

#### Vectors

In [65]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [66]:
x[3]

tensor(3)

In [67]:
len(x)

4

In [68]:
x.shape

torch.Size([4])

#### Matrices

In [72]:
X = torch.arange(20).reshape(5, 4)

In [73]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [74]:
X.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [77]:
A = torch.arange(9).reshape(3, 3)

In [78]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [79]:
A == A.T

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [80]:
B = torch.tensor([[1,2,3], [2, 0 , 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [81]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### Tensors

In [83]:
X = torch.arange(24).reshape(2, 3, 4)

In [84]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [86]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [87]:
B = A.clone()

In [88]:
A + B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [89]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [91]:
#### reduction operations

In [90]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [92]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [93]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [94]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [95]:
A.sum()

tensor(190.)

In [96]:
A.sum(axis=[0, 1])   # same as summing up all elements

tensor(190.)

In [97]:
A.mean()

tensor(9.5000)

In [99]:
A.sum() / A.numel()

tensor(9.5000)

In [100]:
A.mean(axis=1)

tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000])

In [101]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [102]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

#### Non reduction operations

In [107]:
A.sum(axis=1, keepdims=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [108]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [109]:
A / A.sum()   # scalar operations

tensor([[0.0000, 0.0053, 0.0105, 0.0158],
        [0.0211, 0.0263, 0.0316, 0.0368],
        [0.0421, 0.0474, 0.0526, 0.0579],
        [0.0632, 0.0684, 0.0737, 0.0789],
        [0.0842, 0.0895, 0.0947, 0.1000]])

In [111]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [113]:
 A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [114]:
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

### Dot products

In [120]:
y = torch.ones(4, dtype=torch.float32)
x,y

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]))

In [121]:
x.shape, y.shape

(torch.Size([4]), torch.Size([4]))

In [123]:
torch.sum(torch.dot(x, y))

tensor(6.)

In [124]:
torch.sum(x * y)

tensor(6.)

In [125]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [128]:
A.shape, x.shape, torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [129]:
A.shape

torch.Size([5, 4])

In [131]:
B = torch.ones(4, 3)

In [133]:
A.shape, B.shape, torch.mm(A, B).shape

(torch.Size([5, 4]), torch.Size([4, 3]), torch.Size([5, 3]))

#### Norm of vector

In [137]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)   # L2 norm

tensor(5.)

In [139]:
torch.abs(u).sum()   # L1 , norm

tensor(7.)

In [140]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [144]:
B = torch.arange(20).reshape(5, 4)

In [145]:
C = A + B 

In [146]:
A.T + B.T == C.T

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [147]:
A = torch.arange(9).reshape(3, 3)

In [148]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [149]:
C = A + A.T

In [150]:
C

tensor([[ 0,  4,  8],
        [ 4,  8, 12],
        [ 8, 12, 16]])

In [151]:
x = torch.arange(24).reshape(2,3,4)

In [153]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [154]:
len(x)

2

In [157]:
x.size()

torch.Size([2, 3, 4])

In [158]:
x.numel()

24

In [159]:
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [160]:
A.sum()

tensor(36)

In [161]:
A.sum(axis=1)

tensor([ 3, 12, 21])

In [162]:
A / A.sum(axis=1)

tensor([[0.0000, 0.0833, 0.0952],
        [1.0000, 0.3333, 0.2381],
        [2.0000, 0.5833, 0.3810]])

In [164]:
x.shape

torch.Size([2, 3, 4])

In [166]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [165]:
x.sum(axis=0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [169]:
x[0] + x[1]

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [167]:
x.sum(axis=1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [168]:
x.sum(axis=2)

tensor([[ 6, 22, 38],
        [54, 70, 86]])