In [1]:
import torch
import numpy as np
import pandas as pd
import os

## Tensor Operations

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
X.shape

torch.Size([3, 4])

In [8]:
X = x.reshape(3, -1)

In [9]:
X.shape

torch.Size([3, 4])

In [10]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)

tensor([[ 0.5254,  0.4745, -0.9561,  1.3814],
        [ 1.7252, -1.4761,  0.5499, -0.7372],
        [-0.9177,  1.6576, -0.4244, -1.0732]])

In [14]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
torch.arange(5) + torch.arange(5)

tensor([0, 2, 4, 6, 8])

In [16]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [18]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [19]:
torch.cat((X, Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [22]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
X.sum()

tensor(66.)

In [24]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

In [25]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [26]:
(a + b).shape

torch.Size([3, 2])

In [27]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [29]:
X[-1][3]

tensor(11.)

In [30]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X[1][2] = 600.2

In [33]:
X

tensor([[  0.0000,   1.0000,   2.0000,   3.0000],
        [  4.0000,   5.0000, 600.2000,   7.0000],
        [  8.0000,   9.0000,  10.0000,  11.0000]])

In [34]:
X[0:2, :] = 500

In [35]:
X

tensor([[500., 500., 500., 500.],
        [500., 500., 500., 500.],
        [  8.,   9.,  10.,  11.]])

In [36]:
X[0:3, 0:4] = 0

In [37]:
X

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [39]:
before = id(Y)
Y = Y + X
before == id(Y)

False

In [40]:
before = id(Y)
Y[:] = Y + X
before == id(Y)

True

In [41]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y       # used the same object memory (in-place update)
print('id(Z):', id(Z))

id(Z): 140365455501056
id(Z): 140365455501056


In [42]:
A = np.array([1, 2, 3])
B = torch.tensor(A)
A, B

(array([1, 2, 3]), tensor([1, 2, 3]))

In [43]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [44]:
a = torch.tensor([3.5])
a

tensor([3.5000])

In [45]:
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Reading Data into tensor

In [46]:
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')

In [47]:
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # Column names
    f.write('NA,Pave,127500\n') # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [48]:
data = pd.read_csv('data/house_tiny.csv')
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [49]:
inputs = data.iloc[:, :2]
output = data.iloc[:, 2]

In [50]:
inputs = inputs.fillna(inputs.mean())  # filling with mean value

In [51]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [52]:
X = torch.tensor(inputs.values)
y = torch.tensor(output.values)

In [53]:
X, X.shape

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 torch.Size([4, 3]))

In [54]:
y, y.shape

(tensor([127500, 106000, 178100, 140000]), torch.Size([4]))

In [55]:
col_most_nan = data.isnull().sum().sort_values(ascending=False).index[0]

In [56]:
col_most_nan

'Alley'

In [57]:
inputs_rem_most_null = data.drop(labels=col_most_nan, axis=1)

In [58]:
inputs_rem_most_null

NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000

## Linear Algebra on Tensors