In [1]:
import numpy as np

### Creating Arrays

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1, 2, 3, 4.5, 5]) # upcasting based on type

array([1. , 2. , 3. , 4.5, 5. ])

In [4]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [5]:
np.array([range(i, i +3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((2, 4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.full((3, 4), 2.45)

array([[2.45, 2.45, 2.45, 2.45],
       [2.45, 2.45, 2.45, 2.45],
       [2.45, 2.45, 2.45, 2.45]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [12]:
np.random.random((2, 2))

array([[0.9890819 , 0.10953687],
       [0.66975141, 0.04327257]])

In [13]:
np.random.normal(0, 1, (3, 3)) #mean - 0, #std - 1

array([[ 1.04350288,  0.61078459,  0.17485784],
       [-0.50122943, -1.39168426, -1.47289416],
       [-0.23521018,  0.44131845, -0.19362035]])

In [14]:
np.random.randint(0, 10, (3, 3))

array([[6, 8, 6],
       [2, 7, 1],
       [3, 7, 3]])

In [15]:
np.random.randint(0, 6, (2,2))

array([[4, 4],
       [5, 1]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(2, dtype='int')

array([[1, 0],
       [0, 1]])

In [18]:
np.empty(3)

array([1., 1., 1.])

In [19]:
np.ones(5, dtype=np.int16)

array([1, 1, 1, 1, 1], dtype=int16)

### Numpy Array Attributes

In [20]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

In [21]:
print('x3 dim :', x3.ndim)
print('x3 shape :', x3.shape)
print('x3 size :', x3.size)   # total num elements
print('x3 type :', x3.dtype)

x3 dim : 3
x3 shape : (3, 4, 5)
x3 size : 60
x3 type : int64


In [22]:
print('x3 each itemsize :', x3.itemsize , ' bytes')
print('x3 total size in byte :', x3.nbytes, ' bytes')

x3 each itemsize : 8  bytes
x3 total size in byte : 480  bytes


### Indexing Array

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[4]

7

In [25]:
x1[-1]

9

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0, 0]

3

In [28]:
x2[1, 2]

8

In [29]:
x2[2, -1]

7

In [30]:
x2[2, 1] == 6

True

In [31]:
x2[1, 2] = 20    # assignment

In [32]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 20,  8],
       [ 1,  6,  7,  7]])

In [33]:
x2[2]

array([1, 6, 7, 7])

In [34]:
type(x2[1])  # each row is an array for 2 * 2 ndarray

numpy.ndarray

### Array slicing

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [36]:
x1[:2]

array([5, 0])

In [37]:
x1[3:]

array([3, 7, 9])

In [38]:
x1[::2]

array([5, 3, 7])

In [39]:
x1[1::2]

array([0, 3, 9])

In [40]:
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x1[::-1] # start=size, stop=0, step=-1(reverse)

array([9, 7, 3, 3, 0, 5])

In [42]:
x1[-2::-1] # start=-2, stop=0, step=-1(reverse)

array([7, 3, 3, 0, 5])

In [43]:
x1[::-2]  # start=size, stop=0, step=-2(reverse alternate)

array([9, 3, 0])

In [44]:
x1[-2::-2] # start=-2, stop=0, step=-2(reverse alternate)

array([7, 3, 5])

In [45]:
x1[-2:1:-1] # start=-2, stop=1, step=-1(reverse)

array([7, 3, 3])

In [46]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 20,  8],
       [ 1,  6,  7,  7]])

In [47]:
x2[:2, :3]

array([[ 3,  5,  2],
       [ 7,  6, 20]])

In [48]:
x2[:2, ::2]

array([[ 3,  2],
       [ 7, 20]])

In [49]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8, 20,  6,  7],
       [ 4,  2,  5,  3]])

In [50]:
x2[::-1]

array([[ 1,  6,  7,  7],
       [ 7,  6, 20,  8],
       [ 3,  5,  2,  4]])

In [51]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 20,  8],
       [ 1,  6,  7,  7]])

In [52]:
x2[:, 0]

array([3, 7, 1])

In [53]:
x2[1, :]

array([ 7,  6, 20,  8])

In [54]:
x2[1]

array([ 7,  6, 20,  8])

In [55]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

In [56]:
x2_sub[0, 0] = 100

In [57]:
x2

array([[100,   5,   2,   4],
       [  7,   6,  20,   8],
       [  1,   6,   7,   7]])

#### User copy, if we need immutable sub-arrays

In [58]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[100,   5],
       [  7,   6]])

In [59]:
x2_sub_copy[0, 0] = 200

In [60]:
x2

array([[100,   5,   2,   4],
       [  7,   6,  20,   8],
       [  1,   6,   7,   7]])

#### reshaping nd arrays

In [61]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
x = np.array([1,2,3])
x
x.shape

(3,)

In [64]:
y = x.reshape((1, 3))
y.shape

(1, 3)

In [65]:
y

array([[1, 2, 3]])

In [66]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [67]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [68]:
x

array([1, 2, 3])

In [69]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### Concating numpy array

In [70]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
x.shape, y.shape

((3,), (3,))

In [71]:
z = np.concatenate([x, y])
z.shape

(6,)

In [72]:
z

array([1, 2, 3, 3, 2, 1])

In [73]:
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 1, 2, 3, 3, 2, 1])

In [74]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [78]:
x2

array([[100,   5,   2,   4],
       [  7,   6,  20,   8],
       [  1,   6,   7,   7]])

In [79]:
x6 = np.array([[1, 2], [3,4]])
x6

array([[1, 2],
       [3, 4]])

In [80]:
np.concatenate([grid, x6], axis=1)  # on column axis, row count should match

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

In [81]:
x7 = np.array([[1,2, 3], [3, 4, 5]])
x7

array([[1, 2, 3],
       [3, 4, 5]])

In [82]:
np.concatenate([grid, x7], axis=0) #on row axis, column count should match

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [3, 4, 5]])

In [83]:
x = np.array([1, 2, 3])
grid = np.array([[9,8, 7], [6, 5, 4]])

In [84]:
x

array([1, 2, 3])

In [85]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [86]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [87]:
np.vstack([grid, x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [88]:
y = np.array([[99], [99]])
y

array([[99],
       [99]])

In [89]:
np.hstack([grid, y]) # row count should match

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [90]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
x

array([1, 2, 3, 4, 5, 6, 7])

#### splitting numpy arrays

In [91]:
np.split(x, [3, 5])  # split as [:2], [3:4], [5:]

[array([1, 2, 3]), array([4, 5]), array([6, 7])]

In [92]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
upper, lower = np.vsplit(grid, [2])

In [94]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [95]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
left, right = np.hsplit(grid, [2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [97]:
np.hsplit(grid, [1, 2])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]