In [1]:
import numpy as np

### TIME it

In [2]:
def hello(given_num):
    return given_num * 2
%timeit hello(100)

82 ns ± 0.852 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### Ufuncs applied to 1 dimensions also

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [5]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

### Ufuncs apply to 2 dimensions also

In [6]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [8]:
# Basic Arithmetic

In [9]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [10]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [11]:
# order doesn't matter - of course BODMAS matters

In [12]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

### Absolute Value

In [13]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [14]:
# np.absolute, np.abs

In [15]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j]) #complex numbers
x

array([3.-4.j, 4.-3.j, 2.+0.j, 0.+1.j])

In [16]:
np.abs(x)

array([5., 5., 2., 1.])

# Trigonometry

In [17]:
theta = np.linspace(0, np.pi, 3)

In [18]:
theta

array([0.        , 1.57079633, 3.14159265])

In [19]:
# sine, cosine

In [20]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [21]:
# INVERSE sine, cosine

In [22]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponential 

In [23]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


### Logarithms

In [24]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


### When inputs are too small

In [25]:
#when the inputs are very small, we can make some modifications like these to increase precision
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))
# to be discussed

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [41]:
from scipy import special

In [43]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))
# to be discussed

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [45]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))
# to be discussed

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [64]:
x = np.arange(5)
y = np.empty(5)
x, y

(array([0, 1, 2, 3, 4]), array([ 1.,  2.,  4.,  8., 16.]))

In [65]:
np.multiply(x, 10), y

(array([ 0, 10, 20, 30, 40]), array([ 1.,  2.,  4.,  8., 16.]))

In [53]:
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


### Don't waste MEMORY

In [69]:
x = np.arange(5)
y = np.zeros(10)
x, y

(array([0, 1, 2, 3, 4]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [71]:
np.power(3, x), np.power(2, x)

(array([ 1,  3,  9, 27, 81], dtype=int32),
 array([ 1,  2,  4,  8, 16], dtype=int32))

In [72]:
# if you assign the output like this, then first the output will be stored in a temp array and
# then it is copied inot z, this will make operations very slow for huge arrays. DONT DO THIS
z[::2] = np.power(2, x)
z

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [73]:
# Do this instead
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### Reduce

In [74]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [75]:
np.multiply.reduce(x)

120

In [76]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [77]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [81]:
np.sum(x), np.prod(x)

(15, 120)

In [82]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [83]:
np.cumprod(x)

array([  1,   2,   6,  24, 120], dtype=int32)

### Multiplication Table

In [86]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])